package CERP.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;

@Service
public class UserService {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void init() {
        String checkTableSql = "SELECT COUNT(*) FROM user_tables WHERE table_name = 'CER_USERS'";
        Integer tableExists = jdbcTemplate.queryForObject(checkTableSql, Integer.class);

        if (tableExists == 0) {
            String sql = "CREATE TABLE cer_users (" +
                    "u_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "u_name VARCHAR2(50) NOT NULL, " +
                    "email VARCHAR2(100) NOT NULL, " +
                    "password_hash VARCHAR2(255) NOT NULL)";
            jdbcTemplate.execute(sql);
        }
    }

    public void register(String username, String email, String passwordHash){
        String sql = "INSERT INTO cer_users (u_name, email, password_hash) VALUES (?, ?, ?)";
        jdbcTemplate.update(sql, username, email, passwordHash);
    }

    public boolean isUsernameExist(String username){
        // String checkSql = "SELECT COUNT(*) FROM cer_users WHERE u_name = ?";
        // Integer count = jdbcTemplate.queryForObject(checkSql, new Object[]{username}, Integer.class);
        // return count != null && count > 0;
        String checkSql = "SELECT COUNT(*) FROM cer_users WHERE u_name = ?";
        Integer count = jdbcTemplate.queryForObject(checkSql, Integer.class, username);
        return count != null && count > 0;
    }

    public boolean login(String username, String passwordHash) {
        // String sql = "SELECT COUNT(*) FROM cer_users WHERE u_name = ? AND password_hash = ?";
        // Integer count = jdbcTemplate.queryForObject(sql, new Object[]{username, passwordHash}, Integer.class);

        // return count != null && count > 0;
        String sql = "SELECT COUNT(*) FROM cer_users WHERE u_name = ? AND password_hash = ?";
        Integer count = jdbcTemplate.queryForObject(sql, Integer.class, username, passwordHash);

        return count != null && count > 0;
    }
}
